### PR TITLE
getCssRules...: Add support for default XML namespaces in stylesheets

### PR DESCRIPTION
**Pull request by papandreou**
Context: https://gitter.im/assetgraph/assetgraph?at=5dcc8a29e75b2d5a19c9b937

### CODE REVIEW

**Comment by Munter** [comment]
What's wrong with node 12? `TypeError: getCssRulesByProperty is not a function` is not an error I would expect at all, given that the tests pass on the other node versions

**Comment by papandreou** [comment]
@Munter, fixed now, it was a backwards incompatible change that had snuck into font-tracer.

**Comment by Munter** [comment]
I need to figure out how to make coveralls not report tiny coverage decreases as failures. Having any test integration report an error blocks the ability to merge from a mobile phone :(

**Comment by Munter** [comment]
I set this up now:
image

**Comment by papandreou** [comment]
That also makes it useless. They’re using the wrong metric in my opinion. They should only fail the build if the absolute number of uncovered lines increases.

**Pull request merged**
