### PR TITLE
Dynamic traces

### PR DESCRIPTION
**Pull request by papandreou**
Use [font-tracer](https://github.com/assetgraph/assetgraph) in a headless browser to generate traces of the resulting state of static pages.

Relates to #29

Prerequisite: https://github.com/assetgraph/assetgraph/pull/988

TODO:

- [x] Since puppeteer doesn't have the equivalent of a `--root` switch, find a way to get root-relative urls on the page to be resolved correctly. Maybe we have to spin up a local server. _Seems like we might be able to intercept and respond to the network requests instead using https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue_
- [x] Also use font-tracer for the jsdom-based tracing so assetgraph doesn't need to depend on font-tracer directly _Fixed by subfont adopting the `subsetFonts` transform_
- [x] See if we can use puppeteer's "BrowserFetcher" to download the browser itself at runtime the first time `--dynamic` is passed so you don't have to download 100 MB up front when installing subfont.
- [x] Add error handling

### CODE REVIEW

**Comment by papandreou** [comment]
@Munter Input about how to handle the TODOs would be welcome :hugs:

**Comment by papandreou** [comment]
@Munter, this should be ready for a review now.

It's tempting to move all the tracing out of `subsetFonts` and maybe support merging static traces with dynamic ones to get the best of both worlds. I've left that out for now, though.

**Comment by papandreou** [comment]
> and maybe support merging static traces with dynamic ones to get the best of both worlds. I've left that out for now, though.

Implemented in e800cd41c8c2503c776137515f40b47315f606db so that we also do the static trace when `--dynamic` is passed. Thus you don't miss text in `<noscript>` and statically available text that gets removed by JavaScript. Feels like the right compromise.

**Comment by Munter** [comment]
The diff looks a bit weird. I'm getting changes that are also on `master`. Did something go wrong in the reverse merge?

**Comment by papandreou** [comment]
> The diff looks a bit weird. I'm getting changes that are also on `master`. Did something go wrong in the reverse merge?

@Munter, I merged master into this branch a couple of times instead of rebasing, but it kinda looks right to me when I look over the "Files changed" tab? Which parts are you thinking of specifically?

**Comment by Munter** [comment]
I think I might have just seen one the diff for the merge from master to this branch. Everything looks good to go in this one :)

**Pull request merged**
