### PR TITLE
Rearrange so the main export works as a programmatic api (instead of accepting an argv array)

### PR DESCRIPTION
**Pull request by papandreou**
TODO:

- [x] Think about cleaning up some of the options so they have the same name throughout

### CODE REVIEW

**Comment by Munter** [comment]
I like it.

I guess this is a major version, since the api changes?

**Comment by papandreou** [comment]
Technically, yes, but I doubt that anyone has been using the old one?

**Comment by Munter** [comment]
Only me that I know of. I'm fine with making this a patch and just handling it myself

**Comment by papandreou** [comment]
Okay, great, let's roll the dice ;)

We can be nice and send a PR to gatsby-plugin-subfont once it's released, since they're [shelling out](https://github.com/gatsbyjs/gatsby/blob/3d2f82d6909c5ed9621f232b9746cc0196d36193/packages/gatsby-plugin-subfont/src/gatsby-node.js#L21).

**Pull request merged**
