### PR TITLE
Inject unicode-range into the original @font-face declaration when it's missing some of the glyphs that are used

### PR DESCRIPTION
**Pull request by papandreou**
See the discussion here: https://github.com/Munter/netlify-plugin-subfont/issues/55

It fixes the double download when I run subfont on [the test case we use for the missing glyph warning](https://github.com/Munter/subfont/tree/master/testdata/subsetFonts/missing-glyphs).

Fixes Munter/netlify-plugin-subfont#55

### Before

before

### After

after

### CODE REVIEW

**Comment by Munter** [comment]
Looks great. I can't quite remember the details here. Do we know if this behaves well for google fonts?

**Comment by papandreou** [comment]
> Do we know if this behaves well for google fonts?

Yeah, it should work great. Because of the `User-Agent` we use, we get CSS without `unicode-range`:

```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxP.ttf) format('truetype');
}
```

... So it should make a very positive difference :)

**Comment by Munter** [comment]
It's just hat Google fonts fallbacks are still loaded from Google itself. But I guess that just means the addition adds a benefit to self-hosted fonts for now, and when we switch to self-hosted fallback fonts from Google fonts, they will get the benefit as well

**Comment by Munter** [comment]
Just did a manual test with Google hosted fonts. Obviously there is nowhere we can add the unicode-range because google controls the stylesheet. So I was worried that the updated error message was incorrect. But of course, google serves unicode-range to capable browsers, so the error message is still correct even when Google supplies the CSS for the fallback font :D

**Comment by papandreou** [comment]
Ah, right, yes 🤦

You’re right that the fallback CSS that gets async loaded from fonts.googleapis.com won’t benefit from this. We really should self-host that as well.

**Comment by daveredfern** [comment]
Thanks for your hard work fixing this @Munter @papandreou. It’s really appreciated.

**Pull request merged**
