### PR TITLE
Only download truetype files from Google Web Fonts and convert them locally

### LINKED ISSUE #109: Missing glyph fallback detected
In my project I've added link to google fonts:
`<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400&family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,400&display=swap" rel="stylesheet"/>`
and process the resulting html using subfont.

Locally on mac everything works great, but during github action execution on ubuntu-latest I've got following warning (more like an error actually):
```
WARN: Missing glyph fallback detected.
         When your primary webfont doesn't contain the glyphs you use, browsers that don't support unicode-range will load your fallback fonts, which will be a potential waste of bandwidth.
         These glyphs are used on your site, but they don't exist in the font you applied to them:
         - \u{20} ( ) in font-family 'Roboto' (300/normal) at out/ru/course/react/junior/index.html:1:10
         - \u{21} (!) in font-family 'Roboto' (300/normal) at out/ru/course/react/junior/index.html:1:2
         - \u{28} (() in font-family 'Roboto' (300/normal) at out/ru/course/react/junior/index.html:1:223
         - \u{29} ()) in font-family 'Roboto' (300/normal) at out/ru/course/react/junior/index.html:1:242
         - \u{2b} (+) in font-family 'Roboto' (300/normal) at out/ru/course/react/junior/index.html:1:97
...
```
For some reason it only happens for this particular font.
I guess fonts.googleapis.com respond with different css stylesheet depending on OS and environment.
Any ideas of what is happening here and how it could be solved?

### PR DESCRIPTION
**Pull request by papandreou**
Fixes #109, local font conversion tools lifted from https://github.com/Munter/subfont/pull/56

Avoids the problem where we end up with multiple `@font-face` declarations when downloading the woff2 version given enough characters in the subset: https://github.com/Munter/subfont/issues/109#issuecomment-655201332

It causes a small (2%) increase in the size of the woff2 file in one of the test cases: https://github.com/Munter/subfont/pull/115/files#diff-fab359c44278133fd8ef28aafc5b4a2cR479

Not sure if it's significant enough that we should try to track it down.

### CODE REVIEW

**Comment by papandreou** [comment]
```
$ curl -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.835.2 Safari/537.36' 'https://fonts.googleapis.com/css?family=Open+Sans:400&text=Helo&format=woff2'
```

```css
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans Regular'), local('OpenSans-Regular'), url(https://fonts.gstatic.com/l/font?kit=mem8YaGs126MiZpBA-U1V48aHa0AbQ&skey=62c1cbfccc78b4b2&v=v17) format('woff2');
}
```

```
$ curl -o  'https://fonts.googleapis.com/css?family=Open+Sans:400&text=Helo'
```

```css
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans Regular'), local('OpenSans-Regular'), url(https://fonts.gstatic.com/l/font?kit=mem8YaGs126MiZpBA-U1Uo8aHa0AbQ&skey=62c1cbfccc78b4b2&v=v17) format('truetype');
}
```

```
$ curl -s0 -o opensans_helo_google.woff2 'https://fonts.gstatic.com/l/font?kit=mem8YaGs126MiZpBA-U1V48aHa0AbQ&skey=62c1cbfccc78b4b2&v=v17'
$ curl -s0 -o opensans_helo_google.ttf 'https://fonts.gstatic.com/l/font?kit=mem8YaGs126MiZpBA-U1Uo8aHa0AbQ&skey=62c1cbfccc78b4b2&v=v17'
$ node -e "fs=require('fs').promises;(async()=>{await fs.writeFile('opensans_helo_local.woff2', await require('wawoff2').compress(await fs.readFile('opensans_helo_google.ttf')))})()"
$ ls -l opensans_helo_* | cut -d" " -f 5,9
4044 opensans_helo_google.ttf
2500 opensans_helo_google.woff2
2416 opensans_helo_local.woff2
```

... It seems like wawoff2 actually produces a slightly smaller woff2 file than the one we get from Google. The apparent increase in size must be because this upgrades the mock to a newer version of the Open Sans font, then.

Also, according to `diff <(ttx -o - opensans_helo_google.woff2 2>/dev/null) <(ttx -o - opensans_helo_local.woff2 2>/dev/null)` there's no difference in the OpenType data inside the woff2 containers, so we're actually really doing better. Which is interesting, given that [wawoff2](https://github.com/fontello/wawoff2) is a wasm port of Google's own [woff2](https://github.com/google/woff2) library :thinking:

**Comment by Yankovsky** [comment]
As I understand we need woff/woff2 full versions for fallback if it is enabled.

**Comment by Yankovsky** [comment]
TIL about ttx tool from fonttools library.

**Comment by Yankovsky** [comment]
> Also, according to diff <(ttx -o - opensans_helo_google.woff2 2>/dev/null) <(ttx -o - opensans_helo_local.woff2 2>/dev/null) there's no difference in the OpenType data inside the woff2 containers, so we're actually really doing better.

So what is the difference then? Some meta data?

**Comment by papandreou** [comment]
> So what is the difference then? Some meta data?

It must be more efficient brotli compression settings in `wawoff2`. If I use `woff2_decompress` to convert the woff2 that Google Web Fonts provided, then recompress it with `wawoff2`, I also end up with a file that's 2416 bytes long.

**Comment by papandreou** [comment]
> As I understand we need woff/woff2 full versions for fallback if it is enabled.

Yeah, at present the fallback in the Google Web Fonts case consists of us async-loading the original CSS from their servers after the document has loaded: https://github.com/Munter/subfont/blob/8770e73ee06f3dbda846ac2c5a5c5b1bd7c4331f/lib/subsetFonts.js#L220-L245

There are some good things about this, but we've been meaning to also fully self-host the fallback for a long time: https://github.com/Munter/subfont/issues/31

This PR is a step towards that -- I can try looking into it next.

**Pull request merged**
